/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OAuth 2.0 Token Endpoint (token exchange + refresh)
         * @description Issues Auth Genie access tokens via the OAuth 2.0 Token Endpoint (RFC 6749). Supports refresh tokens (RFC 6749) and OAuth 2.0 Token Exchange (RFC 8693) for exchanging an external OIDC ID Token for an Auth Genie access token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": components["schemas"]["TokenExchangeRequest"] | components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description Token(s) issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid client authentication */
                401: {
                    headers: {
                        /** @description Challenge header for HTTP Basic auth. Included on invalid_client responses. */
                        "WWW-Authenticate"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/token/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token
         * @description Revokes a previously issued refresh token so it cannot be used again.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": components["schemas"]["TokenRevokeRequest"];
                };
            };
            responses: {
                /** @description Token revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve user profile claims for the authenticated user
         * @description Returns claims about the authenticated end-user derived from the stable internal identity.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User profile claims */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserInfoResponse"];
                    };
                };
                /** @description Invalid or expired token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/openid-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenID Provider Configuration Information
         * @description Discovery document used by resource servers and clients to find Auth Genie endpoints. Auth Genie is not a full OIDC provider, but it publishes this document to support standardized discovery of `jwks_uri` and related endpoint metadata.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Discovery document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpenIDConfiguration"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * JSON Web Key Set (JWKS)
         * @description Public keys for verifying Auth Genie-issued JWTs. Recommended to remain unversioned.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JWKS */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JWKSResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description OpenID Provider Metadata (RFC 8414 / OIDC Discovery). Auth Genie publishes a minimal, pragmatic subset suitable for discovery of the issuer, JWKS, and relevant endpoints. */
        OpenIDConfiguration: {
            /**
             * Format: uri
             * @description Issuer identifier for Auth Genie access tokens.
             * @example https://api.authgenie.com
             */
            issuer: string;
            /**
             * Format: uri
             * @description URL of the JSON Web Key Set used to verify Auth Genie access tokens.
             * @example https://api.authgenie.com/.well-known/jwks.json
             */
            jwks_uri: string;
            /**
             * Format: uri
             * @description OAuth 2.0 token endpoint.
             * @example https://api.authgenie.com/v1/oauth/token
             */
            token_endpoint?: string;
            /**
             * Format: uri
             * @description UserInfo endpoint.
             * @example https://api.authgenie.com/v1/userinfo
             */
            userinfo_endpoint?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description OAuth 2.0 Token Exchange request (RFC 8693). Use this to exchange an external OIDC ID Token for an Auth Genie access token. */
        TokenExchangeRequest: {
            /** @description Tenant identifier for scoping the request. In v0.1, this may be omitted in single-tenant deployments (server uses a configured default), but multi-tenant behavior requires a tenant-scoped request. If provided, the server must validate it against the authenticated client/tenant configuration. */
            tenant_id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            grant_type: "TokenExchangeRequest";
            /** @enum {string} */
            subject_token_type: "urn:ietf:params:oauth:token-type:id_token";
            /** @description External OIDC ID Token (the "subject token" being exchanged). */
            subject_token: string;
            /** @description Resource server audiences for the Auth Genie access token. If provided, must be a subset of the authenticated client's configured audience allow-list. For `application/x-www-form-urlencoded` requests, encode multiple audiences by repeating the key: `audiences=https://rs1&audiences=https://rs2`. */
            audiences?: string[];
            /** @description Space-delimited OAuth scopes requested for the issued access token (RFC 6749). */
            scope?: string;
            /** @description Optional. Requested type of the issued token (RFC 8693). If omitted, the server issues an access token. */
            requested_token_type?: string;
            /** @description Optional. Resource indicator (RFC 8693). */
            resource?: string;
            /** @description Non-standard. Optional JSON string carrying limited OIDC profile metadata that may not be present in the upstream ID token (e.g., Apple name claims on first sign-in). v0.1 contract: - Only supported for Apple token exchange in v0.1 - Must be a JSON object with allow-listed string fields: `name`, `given_name`, `family_name`, `email` - Unknown fields must be rejected (`invalid_request`) - Intended for display/userinfo only; MUST NOT be used for authorization decisions */
            authgenie_oidc_metadata?: string;
        };
        /** @description OAuth 2.0 Refresh Token grant request (RFC 6749). */
        RefreshTokenRequest: {
            /** @description Tenant identifier for scoping the refresh request. In v0.1, this may be omitted in single-tenant deployments (server uses a configured default). If provided, the server must validate it against the authenticated client/tenant configuration. */
            tenant_id?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            grant_type: "RefreshTokenRequest";
            refresh_token: string;
            /** @description Optional. Space-delimited scopes for the new access token (RFC 6749). If omitted, the scope is typically the same as originally granted. */
            scope?: string;
        };
        /**
         * @description OAuth 2.0 Access Token Response (RFC 6749).
         *     AuthGenie extension: response MAY include a stable `sub` plus an allow-listed subset of upstream profile claims (if available during token exchange). These fields are informational only.
         */
        TokenResponse: {
            access_token: string;
            /**
             * @default Bearer
             * @enum {string}
             */
            token_type: "Bearer";
            expires_in: number;
            refresh_token?: string | null;
            scope?: string | null;
            /**
             * Format: uuid
             * @description AuthGenie stable subject identifier for the user (same value as access token `sub`).
             */
            sub?: string | null;
            /** @description Tenant identifier for the request (same value as access token `tenant_id` claim). */
            tenant_id?: string | null;
            /** @description Optional. Display name derived from upstream claims when available. */
            name?: string | null;
            given_name?: string | null;
            family_name?: string | null;
            /** Format: email */
            email?: string | null;
            email_verified?: boolean | null;
        };
        /** @description Token revocation request (RFC 7009-style). This endpoint is intended for revoking refresh tokens. The server SHOULD respond with 200 even if the token is unknown or already revoked. */
        TokenRevokeRequest: {
            /** @description Tenant identifier for scoping the revoke request. In v0.1, this may be omitted in single-tenant deployments (server uses a configured default). If provided, the server must validate it against the authenticated client/tenant configuration. */
            tenant_id?: string;
            /** @description The token to revoke (typically a refresh token). */
            token: string;
            /**
             * @description Optional hint about the type of the token being revoked.
             * @enum {string|null}
             */
            token_type_hint?: "refresh_token" | null;
        };
        UserInfoResponse: {
            /**
             * Format: uuid
             * @description Stable internal subject identifier for the user (v0.1: UUIDv7).
             */
            sub: string;
            name?: string | null;
            given_name?: string | null;
            family_name?: string | null;
            /** Format: email */
            email?: string | null;
            email_verified?: boolean | null;
            /** Format: uri */
            picture?: string | null;
            locale?: string | null;
            /** @enum {string|null} */
            idp?: "google" | "apple" | null;
            tenant_id?: string | null;
        };
        JWKSResponse: {
            keys: components["schemas"]["JWK"][];
        };
        JWK: {
            /** @enum {string} */
            kty: "RSA";
            kid: string;
            /** @enum {string} */
            use: "sig";
            /** @enum {string} */
            alg: "RS256";
            n?: string | null;
            e?: string | null;
        };
        /** @description OAuth 2.0 error response (RFC 6749). Some fields are optional depending on the error. Common values for `error` in Auth Genie include: `invalid_request`, `invalid_client`, `invalid_grant`, `unauthorized_client`, `invalid_scope`, `unsupported_grant_type`. */
        ErrorResponse: {
            /** @description OAuth 2.0 error code. */
            error: string;
            /** @description Human-readable ASCII text providing additional information (RFC 6749). */
            error_description?: string | null;
            /**
             * Format: uri
             * @description URI identifying a human-readable web page with information about the error (RFC 6749).
             */
            error_uri?: string | null;
            /**
             * @deprecated
             * @description Deprecated. Use error_description.
             */
            message?: string | null;
            request_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
