/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published + canceled trips for the authenticated member */
        get: operations["listVisibleTripsForMember"];
        put?: never;
        /** Create a trip draft */
        post: operations["createTripDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List draft trips visible to the authenticated member */
        get: operations["listMyDraftTrips"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get trip details (visible to member) */
        get: operations["getTripDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a trip (draft or published)
         * @description For drafts: creator-only when private; organizer-only when public. For published: organizer-only.
         */
        patch: operations["updateTrip"];
        trace?: never;
    };
    "/trips/{tripId}/draft-visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set draft visibility for a trip draft */
        put: operations["setTripDraftVisibility"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a trip (idempotent) */
        post: operations["publishTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a trip (idempotent) */
        post: operations["cancelTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/organizers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an organizer to a trip */
        post: operations["addTripOrganizer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/organizers/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an organizer from a trip */
        delete: operations["removeTripOrganizer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set my RSVP for a published trip */
        put: operations["setMyRSVP"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/rsvp/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my RSVP for a trip */
        get: operations["getMyRSVPForTrip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/rsvps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get RSVP summary for a trip */
        get: operations["getTripRSVPSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members (minimal directory) */
        get: operations["listMembers"];
        put?: never;
        /** Create my member profile (self-provision membership) */
        post: operations["createMyMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search members by display name */
        get: operations["searchMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my member profile (resolved from JWT subject) */
        get: operations["getMyMemberProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update my member profile */
        patch: operations["updateMyMemberProfile"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TripStatus: "DRAFT" | "PUBLISHED" | "CANCELED";
        /** @enum {string} */
        DraftVisibility: "PRIVATE" | "PUBLIC";
        /** @enum {string} */
        RSVPResponse: "YES" | "NO" | "UNSET";
        /** @enum {string} */
        ArtifactType: "GPX" | "SCHEDULE" | "DOCUMENT" | "OTHER";
        Location: {
            label: string;
            address?: string | null;
            latitudeLongitude?: {
                /** Format: double */
                latitude?: number;
                /** Format: double */
                longitude?: number;
            } | null;
        };
        TripArtifact: {
            /** @description Stable identifier for this artifact (external_id). */
            artifactId: string;
            type: components["schemas"]["ArtifactType"];
            title: string;
            /** Format: uri */
            url: string;
        };
        /** @description Partial update shape for Location. Omitted fields are unchanged. */
        LocationPatch: {
            label?: string | null;
            address?: string | null;
            latitudeLongitude?: {
                /** Format: double */
                latitude?: number | null;
                /** Format: double */
                longitude?: number | null;
            } | null;
        };
        VehicleProfile: {
            make?: string | null;
            model?: string | null;
            tireSize?: string | null;
            liftLockers?: string | null;
            fuelRange?: string | null;
            recoveryGear?: string | null;
            hamRadioCallSign?: string | null;
            notes?: string | null;
        };
        MemberSummary: {
            memberId: string;
            displayName: string;
            /** Format: email */
            email: string;
            /** Format: email */
            groupAliasEmail?: string | null;
        };
        /** @description Minimal member directory entry (no email fields). */
        MemberDirectoryEntry: {
            memberId: string;
            displayName: string;
        };
        MemberProfile: components["schemas"]["MemberSummary"] & {
            vehicleProfile?: components["schemas"]["VehicleProfile"];
        };
        TripSummary: {
            tripId: string;
            name?: string | null;
            /** Format: date */
            startDate?: string | null;
            /** Format: date */
            endDate?: string | null;
            status: components["schemas"]["TripStatus"];
            /** @description Present only when `status = DRAFT`. Omitted for non-draft trips. */
            draftVisibility?: components["schemas"]["DraftVisibility"];
            /** @description For published trips, capacity is required and must be >= 1. */
            capacityRigs?: number | null;
            /** @description Present only when `status = PUBLISHED`. Omitted for `DRAFT` and `CANCELED`. */
            attendingRigs?: number | null;
        };
        TripDetails: {
            tripId: string;
            name?: string | null;
            description?: string | null;
            /** Format: date */
            startDate?: string | null;
            /** Format: date */
            endDate?: string | null;
            status: components["schemas"]["TripStatus"];
            /** @description Present only when `status = DRAFT`. Omitted for non-draft trips. */
            draftVisibility?: components["schemas"]["DraftVisibility"];
            /** @description For published trips, capacity is required and must be >= 1. */
            capacityRigs?: number | null;
            difficultyText?: string | null;
            meetingLocation?: components["schemas"]["Location"];
            commsRequirementsText?: string | null;
            recommendedRequirementsText?: string | null;
            organizers: components["schemas"]["MemberSummary"][];
            artifacts: components["schemas"]["TripArtifact"][];
            /** @description Present only when `status in (PUBLISHED, CANCELED)`. Omitted for drafts. */
            rsvpSummary?: components["schemas"]["TripRSVPSummary"];
            /** @description Present only when `status in (PUBLISHED, CANCELED)`. Omitted for drafts. */
            myRsvp?: components["schemas"]["MyRSVP"];
            /** @description False for drafts and canceled trips. */
            rsvpActionsEnabled: boolean;
        };
        TripRSVPSummary: {
            /** @description For published trips, capacity is required and must be >= 1. */
            capacityRigs?: number | null;
            attendingRigs: number;
            attendingMembers: components["schemas"]["MemberSummary"][];
            notAttendingMembers: components["schemas"]["MemberSummary"][];
        };
        MyRSVP: {
            tripId: string;
            memberId: string;
            response: components["schemas"]["RSVPResponse"];
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Create a draft trip. Drafts are always created with `draftVisibility = PRIVATE`. */
        CreateTripDraftRequest: {
            /** @description Title. Server trims leading/trailing whitespace and collapses internal whitespace runs before persisting. */
            name: string;
        };
        CreateTripDraftResponse: {
            trip: components["schemas"]["TripCreated"];
        };
        /** @description Minimal response returned when a draft trip is created. */
        TripCreated: {
            tripId: string;
            status: components["schemas"]["TripStatus"];
            draftVisibility: components["schemas"]["DraftVisibility"];
        };
        /** @description Partial update; only provided fields are applied. */
        UpdateTripRequest: {
            /** @description Title. Server trims leading/trailing whitespace and collapses internal whitespace runs before persisting. */
            name?: string;
            description?: string | null;
            /** Format: date */
            startDate?: string | null;
            /** Format: date */
            endDate?: string | null;
            /** @description For published trips, capacity cannot be reduced below the current attending rigs count (YES RSVPs). */
            capacityRigs?: number | null;
            difficultyText?: string | null;
            meetingLocation?: components["schemas"]["LocationPatch"];
            commsRequirementsText?: string | null;
            recommendedRequirementsText?: string | null;
            /** @description Replace the full artifact list for the trip with this ordered list of artifact IDs. */
            artifactIds?: string[] | null;
        };
        TripResponse: {
            trip: components["schemas"]["TripDetails"];
        };
        PublishTripResponse: {
            trip: components["schemas"]["TripDetails"];
            /** @description Prepared announcement copy text for manual posting to the Google Group. */
            announcementCopy: string;
        };
        SetDraftVisibilityRequest: {
            draftVisibility: components["schemas"]["DraftVisibility"];
        };
        AddOrganizerRequest: {
            /** @description Existing member to add as organizer */
            memberId: string;
        };
        SetMyRSVPRequest: {
            response: components["schemas"]["RSVPResponse"];
        };
        SetMyRSVPResponse: {
            myRsvp: components["schemas"]["MyRSVP"];
        };
        /** @description Partial update; only provided fields are applied. */
        UpdateMyMemberProfileRequest: {
            /** @description Display name. Server trims leading/trailing whitespace and collapses internal whitespace runs before persisting. */
            displayName?: string | null;
            /**
             * Format: email
             * @description Member email address. Cannot be cleared. Must be unique across members.
             */
            email?: string;
            /** Format: email */
            groupAliasEmail?: string | null;
            vehicleProfile?: components["schemas"]["VehicleProfile"];
        };
        UpdateMyMemberProfileResponse: {
            member: components["schemas"]["MemberProfile"];
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                } | null;
                requestId?: string | null;
            };
        };
        CreateMemberRequest: {
            /** @description Display name. Server trims leading/trailing whitespace and collapses internal whitespace runs before persisting. */
            displayName: string;
            /** Format: email */
            email: string;
            /** Format: email */
            groupAliasEmail?: string | null;
            vehicleProfile?: components["schemas"]["VehicleProfile"];
        };
        CreateMemberResponse: {
            member: components["schemas"]["MemberProfile"];
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unprocessable Entity */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal Server Error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Trip identifier */
        TripId: string;
        /** @description Member identifier */
        MemberId: string;
        /** @description Search query (display name). Minimum length is 3. */
        SearchQuery: string;
        /** @description If true, include inactive members in the directory list. */
        IncludeInactive: boolean;
        /** @description Optional idempotency key for safely retrying mutating requests. */
        IdempotencyKey: string;
        /** @description Required idempotency key for safely retrying this mutating request. */
        RequiredIdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listVisibleTripsForMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible trips returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        trips: components["schemas"]["TripSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createTripDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description Required idempotency key for safely retrying this mutating request. */
                "Idempotency-Key": components["parameters"]["RequiredIdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripDraftRequest"];
            };
        };
        responses: {
            /** @description Draft created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTripDraftResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
    listMyDraftTrips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft trips returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        trips: components["schemas"]["TripSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getTripDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip identifier */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip details returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTrip: {
        parameters: {
            query?: never;
            header: {
                /** @description Required idempotency key for safely retrying this mutating request. */
                "Idempotency-Key": components["parameters"]["RequiredIdempotencyKey"];
            };
            path: {
                /** @description Trip identifier */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripRequest"];
            };
        };
        responses: {
            /** @description Trip updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
    setTripDraftVisibility: {
        parameters: {
            query?: never;
            header: {
                /** @description Required idempotency key for safely retrying this mutating request. */
                "Idempotency-Key": components["parameters"]["RequiredIdempotencyKey"];
            };
            path: {
                /** @description Trip identifier */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDraftVisibilityRequest"];
            };
        };
        responses: {
            /** @description Draft visibility updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
    publishTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip identifier */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip published (or already published) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishTripResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelTrip: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional idempotency key for safely retrying mutating requests. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Trip identifier */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip canceled (or already canceled) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
    addTripOrganizer: {
        parameters: {
            query?: never;
            header: {
                /** @description Required idempotency key for safely retrying this mutating request. */
                "Idempotency-Key": components["parameters"]["RequiredIdempotencyKey"];
            };
            path: {
                /** @description Trip identifier */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddOrganizerRequest"];
            };
        };
        responses: {
            /** @description Organizer added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
    removeTripOrganizer: {
        parameters: {
            query?: never;
            header: {
                /** @description Required idempotency key for safely retrying this mutating request. */
                "Idempotency-Key": components["parameters"]["RequiredIdempotencyKey"];
            };
            path: {
                /** @description Trip identifier */
                tripId: components["parameters"]["TripId"];
                /** @description Member identifier */
                memberId: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organizer removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
    setMyRSVP: {
        parameters: {
            query?: never;
            header: {
                /** @description Required idempotency key for safely retrying this mutating request. */
                "Idempotency-Key": components["parameters"]["RequiredIdempotencyKey"];
            };
            path: {
                /** @description Trip identifier */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMyRSVPRequest"];
            };
        };
        responses: {
            /** @description RSVP updated (idempotent on same value) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetMyRSVPResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
    getMyRSVPForTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip identifier */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description My RSVP returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        myRsvp: components["schemas"]["MyRSVP"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getTripRSVPSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip identifier */
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RSVP summary returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rsvpSummary: components["schemas"]["TripRSVPSummary"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listMembers: {
        parameters: {
            query?: {
                /** @description If true, include inactive members in the directory list. */
                includeInactive?: components["parameters"]["IncludeInactive"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member directory returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        members: components["schemas"]["MemberDirectoryEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createMyMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberRequest"];
            };
        };
        responses: {
            /** @description Member created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMemberResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Member already exists for the authenticated subject */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
    searchMembers: {
        parameters: {
            query: {
                /** @description Search query (display name). Minimum length is 3. */
                q: components["parameters"]["SearchQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        members: components["schemas"]["MemberDirectoryEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
    getMyMemberProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member profile returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        member: components["schemas"]["MemberProfile"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No provisioned member exists for the authenticated subject */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    updateMyMemberProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description Required idempotency key for safely retrying this mutating request. */
                "Idempotency-Key": components["parameters"]["RequiredIdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyMemberProfileRequest"];
            };
        };
        responses: {
            /** @description Member profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateMyMemberProfileResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No provisioned member exists for the authenticated subject */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalError"];
        };
    };
}
